version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWOR=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local